Fixed: Added contributors section to README.md
modularml/mojo pull request #1193
Opened 2023-10-30 06:47 UTC by Kalyanimhala

Fixed #1184 
Added Contributors section to Readme.
@lattner  kindly view it and merged the PR. Thank You!

2023-10-31 15:44 UTC, Kalyanimhala commented
@jackos Please view my PR!

2023-10-31 16:34 UTC, jackos requested changes
Looks great thanks, if you can please make the requested changes

2023-10-31 16:34 UTC, jackos commented on README.md
> +  <img src="https://contrib.rocks/image?repo=jackos/mojo" />
Repo should be `modularml/mojo` not `jackos/mojo`

2023-10-31 16:34 UTC, jackos commented on README.md
> +### All Thanks To Our Contributors:
Can you please change to `## Thanks To Our Contributors`

`##` will look better

2023-10-31 16:34 UTC, jackos commented on README.md
> +<a href="https://github.com/jackos/mojo/graphs/contributors">
Change to:

`https://github.com/modularml/mojo/graphs/contributors`

2023-11-01 18:54 UTC, jackos approved these changes
Great thanks!

2023-11-01 18:54 UTC, merged