[stdlib] [proposal] Add `del` builtin function
modularml/mojo pull request #3754
Opened 2024-11-07 15:15 UTC by martinvuyk

Add `del` builtin function. I don't like doing `_ = value^`, if there is not going to be support on the language side then at least this function makes the intention of deletion clear. And until we have the `take`/`consume` keyword, the user will have to explicitly transfer `^` the value into the function (AFAIK the compiler will transfer anyway if no further uses are made).

The Mojo formatter seems to not like the definition of a function name equal to the `del` Python keyword and removes parenthesis. Not sure if you guys even want this function or will add support for it in the future. But can this issue be solved downstream? (I imagine you guys just forked black formatter).

If support for this is added on the compiler side later on, it should work the same anyway. Python also accepts:
```python
>>> a, b = "asd", 123
>>> del(a, b)
>>> print(a, b)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'a' is not defined
```

I'll be bold and @Mogball , is support for `del` on the compiler side planned?

2024-11-08 20:57 UTC, lattner requested changes

2024-11-08 20:57 UTC, lattner commented on stdlib/src/builtin/anytype.mojo
> +    del(args)
Why are you passing on the variadic pack here?  you can just use "pass" and the compiler will call the dtors on all the elements for you.

2024-11-08 20:57 UTC, lattner commented on stdlib/src/base64/_b64encode.mojo
> +    del simd_vector^  # We make it live long enough
I don't htink this is necessary, have you tried just removing the `_ = simd_vector`?  I fixed lifetime extension of unsafe pointers.

2024-11-08 20:57 UTC, lattner commented on stdlib/src/builtin/_pybind.mojo
> +    del err^
Similarly, I don't think this manual lifetime extension is necessary, can we just remove it?

2024-11-08 20:57 UTC, lattner commented on stdlib/src/collections/string.mojo
> +        del is_first^
Some of these are needed because there are bugs in the closure handling stuff.

2024-11-08 20:58 UTC, lattner commented
I don't think that this is the right approach.  You can already spell this in mojo with `x.^__del__()`, but we're on a path to fix the bugs that require manual lifetime extension -- we don't want to provide syntax for the bad thing.

2024-11-08 21:10 UTC, martinvuyk commented
Hi @lattner 

ok so the approach will be full auto ASAP destruction then? (and hence no `del` keyword)

> I fixed lifetime extension of unsafe pointers.

sadly there are still some bugs remaining (#3580, #3710), though I think with PR #3734 such foot-guns will be harder to trigger

2024-11-08 21:10 UTC, closed without merging

2024-11-10 01:58 UTC, lattner commented
Let's work through them, thank you for pushing on this (still getting caught up)